<?php
/**
 * Created by PhpStorm.
 * User: user_00
 * Date: 12/20/16
 * Time: 11:10 PM
 */

namespace ScrewTest;


use PHPUnit\Framework\TestCase;
use Screw\Str;


class StrTest extends TestCase
{
    
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
    
    public function testDBC() {

        $str = '!@#%^*()_+{}][;';

        $result = Str::specialCharsToSBC($str);

        $expect = '！＠＃％＾＊（）_＋｛｝〗“;';

        $expect = '！＠＃％＾＊（）_＋｛｝〗“;';

        $this->assertEquals($expect, $result, 'convert to SBC error');

        $str = '腾讯科技(深圳)有限公司';
        $expect = '腾讯科技（深圳）有限公司';

        $result = Str::specialCharsToSBC($str);
        
        println($result);
        println($str);

        $this->assertEquals($expect, $result, 'name convert to SBC error');

    }
    
    public function testRandom()
    {
        $len = 16;
        $str = Str::random($len);
        $this->assertEquals(16, strlen($str), 'random error');
    }
    
    public function testRandomDigit()
    {
        
        $len = 5;
        $space = '0123456789';
        $ret = Str::randomByCharsSpace($len, $space);
        $this->assertEquals($len, strlen($ret), 'random digit error');
        
    }
    
    public function testRandom62()
    {
        $len = 5;
        $ret = Str::random62($len);
        println($ret);
    
        $this->assertEquals($len, strlen($ret), 'random alphabet and digit error');
    }
    
    public function testRandomStr()
    {
        $len = 5;
        $ret = Str::randomAlphabetAndDigit($len);
        println($ret);
        
        $this->assertEquals($len, strlen($ret), 'random by space error');
    }

    public function testToUpperCamelCase() {
        $tmp = 'user_name';
        $this->assertEquals('UserName', Str::toUpperCamelCase($tmp));
    }

    public function testToLowerCamelCase() {
        $tmp = 'user_name';
        $this->assertEquals('userName', Str::toLowerCamelCase($tmp));
    }

    public function testToSnakeCase() {
        $tmp = 'userName';
        $this->assertEquals('user_name', Str::toSnakeCase($tmp));

        $tmp = 'UserName';
        $this->assertEquals('user_name', Str::toSnakeCase($tmp));
    }
}
